SELECT t.PRODUCT_ID, t.PRODUCT_NAME, SUM(r.AMOUNT*t.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT t JOIN FOOD_ORDER r ON t.PRODUCT_ID = r.PRODUCT_ID
WHERE r.PRODUCE_DATE LIKE '2022-05%'
GROUP BY t.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, t.PRODUCT_ID