SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID
JOIN PATIENT p ON p.PT_NO = a.PT_NO
WHERE a.APNT_CNCL_YMD IS NULL
AND a.APNT_YMD LIKE '2022-04-13%'
AND a.MCDP_CD = 'CS'
ORDER BY a.APNT_YMD; 
