SELECT u.USER_ID, u.NICKNAME, SUM(d.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD d ON u.USER_ID = d.WRITER_ID
WHERE d.STATUS = 'DONE'  
GROUP BY u.USER_ID, u.NICKNAME
HAVING SUM(d.PRICE) >= 700000  
ORDER BY TOTAL_SALES ASC